UserSupport/WebApp/Models/ErrorViewModel.cs
using System;

namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UserSupport/WebApp/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL;
using Domain;
using Repositories;

namespace WebApp.Controllers
{
    public class RequestsController : Controller
    {
        private readonly IRequestRepository _requestRepository;

        public RequestsController(IRequestRepository requestRepository)
        {
            _requestRepository = requestRepository;
        }

        // GET: Requests
        public async Task<IActionResult> Index()
        {
            var requests = await _requestRepository.ListAsync();
            var sortedRequests = requests.OrderBy(a => a.Deadline).ToList();
            foreach (var request in sortedRequests.Where(request => request.Deadline.Subtract(DateTime.Now).Hours <= 1))
            {
                request.TextColor = "red";
            }
            return View(sortedRequests);
        }
        

        // GET: Requests/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Requests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Description,Deadline")] Request request)
        {
            request.TimePosted = DateTime.Now;
            if (!ModelState.IsValid) return View(request);
            await _requestRepository.AddAsync(request);
            return RedirectToAction(nameof(Index));
        }
        

        // POST: Requests/Delete/5
        [HttpPost, ActionName("Solve")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Solve(int id)
        {
            await _requestRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
        
    }
}

UserSupport/WebApp/Views/Requests/Create.cshtml
@model Domain.Request

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Request</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UserSupport/WebApp/Views/Requests/Index.cshtml
@model IEnumerable<Domain.Request>

@{
    ViewData["Title"] = "Index";
}

<h1>Requests</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimePosted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deadline)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
    @if (item.TextColor == "red") 
    {
    <tr class="p-3 mb-2 bg-danger text-white">
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TimePosted)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Deadline)
                </td>
                <td>
                <form asp-action="Solve" asp-route-id="@item.Id">
                    <input type="submit" value="Solve" class="btn btn-primary"/> 
                </form>
                </td>
            </tr>
    }
    else
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td> 
                @Html.DisplayFor(modelItem => item.TimePosted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deadline)
            </td>
            <td>
            <form asp-action="Solve" asp-route-id="@item.Id">
                <input type="submit" value="Solve" class="btn btn-primary" /> 
            </form>
            </td>
        </tr> 
    }
        
       
    

}
    </tbody>
</table>

UserSupport/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Requests</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Requests" asp-action="Index">Requests</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Gregor Rehand - AgileWorks testtöö
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>